global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sessions-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/q/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'speakers-service'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/q/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
