apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: do378-expense
    name: do378-expense
  spec:
    selector:
      matchLabels:
        deployment: do378-expense
    template:
      metadata:
        labels:
          deployment: do378-expense
      spec:
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
        containers:
        - name: do378-expense
          image: localhost/expense-restful-service:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
          - name: EXPENSE_MAX_AMOUNT
            value: "2000"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: do378-expense
    name: do378-expense
  spec:
    type: NodePort
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
    selector:
      deployment: do378-expense

