# Dev Services
quarkus.datasource.devservices.image-name = postgres:14.1
quarkus.kafka.devservices.image-name = redpandadata/redpanda:v23.2.10

# Incoming Channels
mp.messaging.incoming.new-speakers-in.connector = smallrye-kafka
mp.messaging.incoming.new-speakers-in.topic = speaker-was-created
mp.messaging.incoming.new-speakers-in.auto.offset.reset = earliest
mp.messaging.incoming.new-speakers-in.value.deserializer = com.bcp.serde.SpeakerWasCreatedDeserializer

# Outgoing Channels

