#false es graalvm
#true seria con quarkus.native.builder-image
quarkus.native.container-build = false
# podman
quarkus.native.container-runtime = docker 
# linux/amd64, windows docker desktop
# no funciona en arm64 como Mac M1, M2, M3, M4
quarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.1-java21

#quarkus.container-image.build=true